//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBlogEngine.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        public int CommentId { get; set; }
        public int PostId { get; set; }
        public string Comment { get; set; }
        public string Source { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
